//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace EDMDAL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DESEDMEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DESEDMEntities object using the connection string found in the 'DESEDMEntities' section of the application configuration file.
        /// public DESEDMEntities() : base("metadata=res://*/DESEDM.csdl|res://*/DESEDM.ssdl|res://*/DESEDM.msl;provider=System.Data.SqlClient;provider connection string=&quot;Data Source=BARAN-VAIO;Initial Catalog=DESEDM;Integrated Security=True;MultipleActiveResultSets=True&quot;", 
        /// </summary>
        //public DESEDMEntities() : base("name=DESEDMEntities", "DESEDMEntities")
        public DESEDMEntities() : base("metadata=res://*/DESEDM.csdl|res://*/DESEDM.ssdl|res://*/DESEDM.msl;provider=System.Data.SqlClient;provider connection string='Data Source=BARAN-VAIO;Initial Catalog=DESEDM;Integrated Security=True;MultipleActiveResultSets=True'",  "DESEDMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DESEDMEntities object.
        /// </summary>
        public DESEDMEntities(string connectionString) : base(connectionString, "DESEDMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DESEDMEntities object.
        /// </summary>
        public DESEDMEntities(EntityConnection connection) : base(connection, "DESEDMEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<DESContent> DESContents
        {
            get
            {
                if ((_DESContents == null))
                {
                    _DESContents = base.CreateObjectSet<DESContent>("DESContents");
                }
                return _DESContents;
            }
        }
        private ObjectSet<DESContent> _DESContents;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the DESContents EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDESContents(DESContent dESContent)
        {
            base.AddObject("DESContents", dESContent);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="DESEDMModel", Name="DESContent")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class DESContent : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new DESContent object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static DESContent CreateDESContent(global::System.Int32 id)
        {
            DESContent dESContent = new DESContent();
            dESContent.Id = id;
            return dESContent;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int32 _Id;
        partial void OnIdChanging(global::System.Int32 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String InputFileName
        {
            get
            {
                return _InputFileName;
            }
            set
            {
                OnInputFileNameChanging(value);
                ReportPropertyChanging("InputFileName");
                _InputFileName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InputFileName");
                OnInputFileNameChanged();
            }
        }
        private global::System.String _InputFileName;
        partial void OnInputFileNameChanging(global::System.String value);
        partial void OnInputFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] InputFileContent
        {
            get
            {
                return StructuralObject.GetValidValue(_InputFileContent);
            }
            set
            {
                OnInputFileContentChanging(value);
                ReportPropertyChanging("InputFileContent");
                _InputFileContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("InputFileContent");
                OnInputFileContentChanged();
            }
        }
        private global::System.Byte[] _InputFileContent;
        partial void OnInputFileContentChanging(global::System.Byte[] value);
        partial void OnInputFileContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OutputFileName
        {
            get
            {
                return _OutputFileName;
            }
            set
            {
                OnOutputFileNameChanging(value);
                ReportPropertyChanging("OutputFileName");
                _OutputFileName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OutputFileName");
                OnOutputFileNameChanged();
            }
        }
        private global::System.String _OutputFileName;
        partial void OnOutputFileNameChanging(global::System.String value);
        partial void OnOutputFileNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] OutputFileContent
        {
            get
            {
                return StructuralObject.GetValidValue(_OutputFileContent);
            }
            set
            {
                OnOutputFileContentChanging(value);
                ReportPropertyChanging("OutputFileContent");
                _OutputFileContent = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OutputFileContent");
                OnOutputFileContentChanged();
            }
        }
        private global::System.Byte[] _OutputFileContent;
        partial void OnOutputFileContentChanging(global::System.Byte[] value);
        partial void OnOutputFileContentChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HashInput
        {
            get
            {
                return _HashInput;
            }
            set
            {
                OnHashInputChanging(value);
                ReportPropertyChanging("HashInput");
                _HashInput = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HashInput");
                OnHashInputChanged();
            }
        }
        private global::System.String _HashInput;
        partial void OnHashInputChanging(global::System.String value);
        partial void OnHashInputChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String HashOutput
        {
            get
            {
                return _HashOutput;
            }
            set
            {
                OnHashOutputChanging(value);
                ReportPropertyChanging("HashOutput");
                _HashOutput = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("HashOutput");
                OnHashOutputChanged();
            }
        }
        private global::System.String _HashOutput;
        partial void OnHashOutputChanging(global::System.String value);
        partial void OnHashOutputChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Trivia
        {
            get
            {
                return _Trivia;
            }
            set
            {
                OnTriviaChanging(value);
                ReportPropertyChanging("Trivia");
                _Trivia = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Trivia");
                OnTriviaChanged();
            }
        }
        private global::System.String _Trivia;
        partial void OnTriviaChanging(global::System.String value);
        partial void OnTriviaChanged();

        #endregion

    
    }

    #endregion

    
}
